encoding: UTF-8
title: Robert Shaffer
email: shafferr@upenn.edu

description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral Fellow, University of Pennsylvania

twitter_username: rbshaffer_
github_username: rbshaffer

include: ['_pages', '_includes']
