encoding: UTF-8
title: Robert Shaffer
email: rbshaffe@maxwell.syr.edu

description: > # this means to ignore newlines until "baseurl:"
  Postdoctoral Fellow, Syracuse University

twitter_username: rbshaffer_
github_username: rbshaffer

include: ['_pages', '_includes']
