encoding: UTF-8
title: Robert Shaffer
email: rbshaffer0@gmail.com

description: > # this means to ignore newlines until "baseurl:"
  Program Manager, BlueLabs Analytics

twitter_username: rbshaffer_
github_username: rbshaffer

include: ['_pages', '_includes']
