theme: jekyll-theme-minimal
title: Robert Shaffer
email: rbshaffer@utexas.edu

description: > # this means to ignore newlines until "baseurl:"
  PhD Student, Government/Statistics, UT Austin.

twitter_username: rbshaffer_
github_username: rbshaffer

include: ['_pages', '_includes']
